import { Container, Divider, Heading, Input, InputGroup, InputRightAddon, InputRightElement } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import Tellonym from '../components/Tellonym';

const Home: NextPage = () => {
  const [input, setInput] = useState("Wpisz tellonyma! Tym razem obsługuje emotki 😎😎");


  return (
    <div>
      <Head>
        <title>Telloner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container mt={6}>
        <Heading>Telloner</Heading>
        <InputGroup mt={3} mb={3}>
          <Input type="text" value={input} onChange={(e) => setInput(e.target.value)} />
          <InputRightAddon>Wklej</InputRightAddon>

        </InputGroup>
        <Tellonym value={input} />
      </Container>

    </div>
  );
};

export default Home;;
